### ISSUE TITLE
How to preprocess the given distilled data?

### ISSUE THREAD

**Issue by yfzhang114** [facebookresearch/DisCo#10]
The given distilled en-ro dataset is composed by
![image](https://user-images.githubusercontent.com/53161950/120481690-f11a7400-c3e2-11eb-9f3b-d9000b504943.png)

while if I run the preprocess.py, I will get an error as follows
![image](https://user-images.githubusercontent.com/53161950/120482095-5ec6a000-c3e3-11eb-9a4a-dba06a4fa620.png)

**Comment by jungokasai** [comment]
My guess is that you need to change `--{train,valid,test}pref`. Did you do something like `--trainpref path-to-dir/train.en-ro`?

**Comment by yfzhang114** [comment]
> My guess is that you need to change `--{train,valid,test}pref`. Did you do something like `--trainpref path-to-dir/train.en-ro`?

It works! Many thanks

**Comment by yfzhang114** [comment]
Done
