### ISSUE TITLE
use disco to training autoregressive model

### ISSUE THREAD

**Issue by NonvolatileMemory** [facebookresearch/DisCo#3]
Hi, Jungo. Thanks for your nice code!

I wanna use your disco model to train an autoregressive model as you said in your paper (sec 5.1 : AT with Contextless KVs). I saw there is one args called at-only in the disco_transformer.py, but I am confused how it used to train the AT model.

Additionally, the q_mask[:, :, eos] is always set to True. Does that means even for AT model we need to predict eos and the corresponded position first?

**Comment by jungokasai** [comment]
Hi! 
Thank you for your interest in our paper! 
Yes, there is indeed an `--at-only` masking option, an implementation of which I deleted in this final version. 
As you pointed out, in an autoregressive decoder, we should do future masking and not attend to `eos`. 
If you want to replicate/explore autoregressive modeling with context keys and values, however, I would recommend that you use the [code for autoregressive models](https://github.com/facebookresearch/DisCo/blob/master/fairseq/models/transformer.py) as a base class; beam search and incremental decoding are all implemented there, [which isn't in my non-autoregressive code](https://github.com/facebookresearch/DisCo/blob/master/fairseq/models/disco_transformer.py#L216). 

Specifically, I would suggest you add [this new architecture](https://github.com/facebookresearch/DisCo/pull/4/commits/b7b31c40413c67ffa5b4f06e9a4615c9a552cb26)  to this code base. The core change is basically [separation of k, v and q input vectors](https://github.com/facebookresearch/DisCo/pull/4/commits/b7b31c40413c67ffa5b4f06e9a4615c9a552cb26#diff-0e4b97fbc37a0e99a7ad5c0dba13af20R158-R165). 

I hope this helps!

**Comment by NonvolatileMemory** [comment]
Got it! Thank you.

**Comment by NonvolatileMemory** [comment]
Hi, Jungo. I use your code to train the AR model, for the distilled wmt 14 en-de dataset(provided by you), I could got 26+ bleu, while for the non-distilled dataset (stanford dataset), I could only get 23.6+. I'm a littile confused, could you share your fairseq shell?

BTW, I think it's a little different in transformerkv and disco. In the first layer of disco, we use position embedding as attention query, while in transformerkv we use the {t-1}-th token. I'm wondering which model used by you in the sec 5.1.

Thank you.

**Comment by jungokasai** [comment]
Hmm, that seems a bit strange. How many GPUs and what `--update-freq`  did you have? Small batch sizes can greatly hurt performance.

I used this `transformer_kv` for this experiment, so it should be the same implementation. Here's the command I used:
```
python train.py ~/data-bin/wmt16.s2s.en-de/ --arch transformer_kv --share-all-embeddings \
--criterion label_smoothed_cross_entropy --label-smoothing 0.1 --lr 5e-4 --warmup-init-lr 1e-7 \
--min-lr 1e-9 --lr-scheduler inverse_sqrt --warmup-updates 4000 --optimizer adam --adam-betas '(0.9, 0.98)' \
--max-tokens 4096 --dropout 0.2 --encoder-layers 6 --encoder-embed-dim 512 \
--decoder-layers 6 --decoder-embed-dim 512 --max-update 300000  --distributed-world-size 16 \
--distributed-port 54106 --fp16 --max-source-positions 10000 --max-target-positions 10000 \
--save-dir  <path_to_dir>  --seed 1 \
```

**Comment by NonvolatileMemory** [comment]
That's my shell here
` CUDA_VISIBLE_DEVICES=11,12,13,14 nohup python -u train.py $DATA_PATH\
  -s en \
  -t de \
  --lr 0.0007 \
  --min-lr 1e-09 \
  --weight-decay 0.0 \
  --clip-norm 0.0 \
  --dropout 0.1 \
  --max-tokens 4096 \
  --update-freq 1 \
  --arch transformer_real_kv \
  --encoder-layers 6 \
  --decoder-layers 6 \
  --optimizer adam \
  --adam-betas '(0.9, 0.98)' \
  --lr-scheduler inverse_sqrt \
  --warmup-init-lr 1e-07 \
  --warmup-updates 4000 \
  --save-dir $SAVE_PATH \
  --tensorboard-logdir results/$DATA/logs \
  --criterion label_smoothed_cross_entropy \
  --label-smoothing 0.1 \
  --no-progress-bar \
  --log-format simple \
  --log-interval 100 \
  --save-interval-updates 2000 \
  --max-update 1000000 \
  --max-epoch 100 \
  --keep-last-epochs 1 \
  --keep-interval-updates 1 \`

**Comment by NonvolatileMemory** [comment]
I will try your shell, thank you!

**Comment by jungokasai** [comment]
Thanks. If you don't have many GPUs, you can always increase `--update-freq`. If you only have 4 GPUs available, you can do `--update-freq 4` to simulate my 16-GPU training.

**Comment by NonvolatileMemory** [comment]
Thanks for your advices, you are so rich!

**Comment by jungokasai** [comment]
Haha, I was (past tense). This is my internship work... Anyways, please keep me posted.
