### ISSUE TITLE
Would you like to share other distilled datasets ?

### ISSUE THREAD

**Issue by NonvolatileMemory** [facebookresearch/DisCo#5]
Hi, Jungo. Thanks for your nice code!

Would you like to share other distilled datasets ?

**Comment by jungokasai** [comment]
Sure.
[WMT16 DE-EN](https://drive.google.com/uc?id=1i6i9sN9Q_Gufcy1GMI2LiNz0UPkSz9QX)
[WMT16 EN-RO](https://drive.google.com/uc?id=11ih_yQQ6nuAkANdvwqvZSyqYA0UKBxyb)
[WMT16 RO-EN](https://drive.google.com/uc?id=1w_uWBXcg5nu1nBidGnHIf83GFAlQYXUk)
[WMT17 EN-ZH](https://drive.google.com/uc?id=1AmMGpW8bdAecDhIu4dA8bmYds_4olYyx)
[WMT17 ZH-EN](https://drive.google.com/uc?id=1gX9HVmSxb3JFBJukplRkdLODYqO8-YWp)

**Comment by shawnkx** [comment]
Thanks! Could you tell us the model to distill the original data? e.g., for WMT De-EN, it is from the transformer big. Thanks!

**Comment by jungokasai** [comment]
Yes as noted in the [paper](https://arxiv.org/abs/2001.05136),
EN-DE, DE-EN, EN-ZH, and ZH-EN: transformer large
EN-RO, and RO-EN: transformer base

**Comment by chynphh** [comment]
@jungokasai  hi, Jungo. Thanks for sharing distilled datasets. But I found that the ‘valid.ro-en.ro’ file is missing in WMT16 RO-EN. Could you please update it?

**Comment by NonvolatileMemory** [comment]
> @jungokasai hi, Jungo. Thanks for sharing distilled datasets. But I found that the ‘valid.ro-en.ro’ file is missing in WMT16 RO-EN. Could you please update it?

Hi @chynphh , the validation is not distilled data. So you could adopt valid.en-ro.ro valid.en-ro.en from wmt16 EN-RO dataset. That should be the same as WMT 16 RO-EN.

**Comment by jungokasai** [comment]
Thank you for this, @NonvolatileMemory! Yes, that's right. Please use the EN-RO validation data. More recent WMT data have different evaluation data for different directions to address the translationese problem, but not in 2016...

**Comment by chynphh** [comment]
@NonvolatileMemory @jungokasai  Thanks!!

**Comment by jungokasai** [comment]
Could you close this issue? I don't have permission to do so at the moment.

**Comment by NonvolatileMemory** [comment]
Hi, Jungo. Thanks for your data!

Would you like to share wmt 14 en-de unbinarized data ?

**Comment by jungokasai** [comment]
You can recover the unbinarized data using this: https://github.com/facebookresearch/DisCo/blob/master/scripts/read_binarized.py.
