### ISSUE TITLE
distilled validation data

### ISSUE THREAD

**Issue by shawnkx** [facebookresearch/DisCo#6]
Hi, thanks for providing the distillation data. I found the validate set in the data is raw data. Do you distill the validation set? Thanks!

**Comment by jungokasai** [comment]
Thank you for catching this. We used **raw data** for validation.

**Comment by shawnkx** [comment]
Did you use the valid loss or value bleu to determine the best model during training?

**Comment by jungokasai** [comment]
Used validation BLEU and averaged top 5 models. See [Sec 4.2](https://arxiv.org/pdf/2001.05136.pdf).

**Comment by jungokasai** [comment]
You can recover the unbinarized data using this: https://github.com/facebookresearch/DisCo/blob/master/scripts/read_binarized.py.
