### ISSUE TITLE
Would you like to share trained CMLM transformers ?

### ISSUE THREAD

**Issue by chynphh** [facebookresearch/DisCo#9]
The CMLM models you implemented generally got better performance than the original models. I'm doing some tests and eager to do some comparisons between models. Would you like to share your trained CMLM transformers ? Thanks!

**Comment by jungokasai** [comment]
Sorry but unfortunately I do not have access to my trained CMLM models anymore. We took the [original implementation](https://github.com/facebookresearch/Mask-Predict) from the paper. As noted in the paper, the difference in the final BLEU scores comes from dropout tuning and averaging checkpoints with 5 top BLEU scores in validation ([Sec. 4.3](https://arxiv.org/pdf/2001.05136.pdf)). We ended up using `--dropout 0.2` in WMT EN-DE. The full training command would be the following: 
```
python train.py ${output_dir}/data-bin --arch bert_transformer_seq2seq \
    --criterion label_smoothed_length_cross_entropy --label-smoothing 0.1 --lr 5e-4 \
    --warmup-init-lr 1e-7 --min-lr 1e-9 --lr-scheduler inverse_sqrt --warmup-updates 10000 \
    --optimizer adam --adam-betas '(0.9, 0.999)' --adam-eps 1e-6 --task translation_self \
    --max-tokens 8192 --weight-decay 0.01 --dropout 0.2 --encoder-layers 6 --encoder-embed-dim 512 \
    --decoder-layers 6 --decoder-embed-dim 512 --fp16 --max-source-positions 10000 \
    --max-target-positions 10000 --max-update 300000 --seed 1 \
    --save-dir ${model_dir} --share-all-embeddings
```

**Comment by chynphh** [comment]
@jungokasai Thanks! I'll try it!
